//
//  File.swift
//  testApp
//
//  Created by Evan Susanto on 10/04/22.
//

import Foundation
//Isi Zat Gizi

let Protein=ZatGizi(titleGizi: "Protein", definisiGizi: "Pada ibu hamil, Protein berguna sebagai komponen penyusun sel vital terutama untuk menciptakan kulit, otot, rambut, dan tulang. Protein Sangat dibutuhkan untuk memastikan pertumbuhan bayi normal dan mencegah berat lahir rendah serta menjaga kesehatan jaringan tubuh si Ibu.")
let VitaminA=ZatGizi(titleGizi: "Vitamin A", definisiGizi: "Pada ibu hamil, Vitamin A berguna untuk proses perkembangan jantung, paru-paru, ginjal, mata, dan Tulang janin. Setelah melahirkan, vitamin A membantu memperbaiki jaringan tubuh ibu, menurunkan resiko terjadinya infeksi, memperkuat daya tahan tubuh, dan menjaga kesehatan penglihatan.")
let VitaminB1=ZatGizi(titleGizi: "Vitamin B1", definisiGizi: "Pada ibu hamil, Vitamin B1 atau Thiamin berguna untuk perkembangan otak, sistem saraf, otot, dan jantung janin serta mencegah penyakit beri-beri pada Ibu. Selain itu, vitamin ini juga dapat mengubah karbohidrat menjadi energi, sehingga tubuh tidak terasa lemas saat hamil.")
 
let VitaminB2=ZatGizi(titleGizi: "Vitamin B2", definisiGizi: "Pada ibu hamil, Vitamin B2 atau Riboflavin berguna untuk mencerahkan kulit Ibu saat masa kehamilan serta konsumsi vitamin ini setiap hari dapat mencegah resiko pre-eklampsia sejak dini. Vitamin B2 Tidak disimpan oleh tubuh sehingga harus rajin dikonsumsi setiap harinya.")
 
let VitaminB3=ZatGizi(titleGizi: "Vitamin B3", definisiGizi: "Pada ibu hamil, Vitamin B3 atau Niasin berguna untuk mengurangi rasa mual serta melancarkan pencernaan ibu hamil. Selain itu, Vitamin B3 pun membantu perkembangan otak, sistem saraf, dan kesehatan kulit si janin.")
 
let VitaminB6=ZatGizi(titleGizi: "Vitamin B6", definisiGizi: "Pada ibu hamil, Vitamin B6 atau Piridoksin berguna untuk perkembangan sistem saraf dan otak janin setiap minggu selama kehamilan. Konsumsi vitamin B6 pun menjaga kadar glukosa serta menghindari berat badan lahir rendah (BBLR) dan cacat saat lahir.")
 
let VitaminB9=ZatGizi(titleGizi: "Vitamin B9", definisiGizi: "Pada ibu hamil, Vitamin B9 (mengandung Asam Folat) sangatlah berguna dan penting. Manfaat mulai dari menunjang pertumbuhan plasenta, mengurangi resiko bayi cacat lahir seperti spina bifida dan bibir sumbing, mengurangi risiko pre-eklampsia, cacat jantung, serta mencegah anemia.")
 
let VitaminB12=ZatGizi(titleGizi: "Vitamin B12", definisiGizi: "Pada ibu hamil, Vitamin B12 atau Cobalamin berguna untuk menjaga kesehatan sistem saraf ibu hamil, serta ketika dikombinasikan dengan asam folat, vitamin ini membantu mencegah spina bifida dan cacat lahir sistem saraf tulang belakang.")
 
//=============================================================================
 
let VitaminC=ZatGizi(titleGizi: "Vitamin C", definisiGizi: "Pada ibu hamil, Vitamin C berguna untuk melindungi dan menjaga kesehatan sel tubuh baik sang Ibu mauapun bayi nya. Selain itu, Vitamin C membantu pembentukan kolagen dalam tulang, otot, kulit, dan pembuluh darah Serta menangkal efek radikal bebas, memperbaiki jaringan tubuh yang rusak, dan mempercepat proses penyembuhan luka.")
 
let VitaminD=ZatGizi(titleGizi: "Vitamin D", definisiGizi: "Pada ibu hamil, Vitamin D berguna untuk perkembangan tulang, gigi, dan fungsi otot bayi agar optimal. Kebutuhan Vitamin D pada ibu hamil biasanya memerlukan bantuan suplementasi dan tidak dapat hanya melalui berjemur dan asupan makanan.")
 
let VitaminE=ZatGizi(titleGizi: "Vitamin E", definisiGizi: "Pada ibu hamil, Vitamin E berguna sebagai antioksidan yang memastikan pembentukan dan perkembangan sel-sel sehat pada janin dan melindungi Ibu hamil dari racun. Vitamin E yang cukup dapat mencegah penuaan plasenta, cedera endotel vaskular, kejadian gangguan hipertensi kehamilan, solusio plasenta, dan kelahiran prematur. Namun, asupan vitamin E yang berlebihan pun dapat mempengaruhi penyerapan dan fungsi vitamin lain yang larut dalam lemak.")
 
let VitaminK=ZatGizi(titleGizi: "Vitamin K", definisiGizi: "Pada ibu hamil, Vitamin K berguna untuk membantu produksi berbagai protein yang dibutuhkan tubuh dalam proses pembekuan darah, dan pembentukan tulang sehingga mencegah pendarahan yang berlebihan, serta menjaga kesehatan jantung dan tulang.")
//=============================================================================
 
let Kalsium=ZatGizi(titleGizi: "Kalsium", definisiGizi: "Pada ibu hamil, Kalsium berguna untuk pembentukan tulang dan gigi. Tubuh Tidak dapat memproduksi kalsium sendiri, sehingga harus dipenuhi dari makanan yang kaya akan kalsium atau melalui suplemen tambahan.")
 
let Fosfor=ZatGizi(titleGizi: "Fosfor", definisiGizi: "Pada ibu hamil, Fosfor berguna untuk mendukung kepadatan tulang dan gigi ibu dan janin dalam kandungan. Selain itu, fosfor juga dibutuhkan untuk kontraksi otot, fungsi ginjal, perbaikan sel dan jaringan tubuh, serta menjaga detak jantung agar tetap normal.")
 
let Magnesium=ZatGizi(titleGizi: "Magnesium", definisiGizi: "Pada ibu hamil, Magnesium berguna untuk menjaga fungsi kekebalan tubuh, pertumbuhan janin dan mencegah kelahiran prematur. Selain itu, mineral ini juga dapat mengurangi stres, menghindari stroke, dan mencegah hipertensi.")
 
let ZatBesi=ZatGizi(titleGizi: "Zat Besi", definisiGizi: "Pada ibu hamil, Zat Besi berguna untuk pembentukan sel darah merah dan hemoglobin yang dibutuhkan untuk memasok oksigen serta nutrisi ke tubuh Ibu dan janin. Kebutuhan zat besi pada ibu hamil meningkat pesat karena adanya peningkatan volume darah ibu yang kisaran umumnya hampir 50%.")
 
let Yodium=ZatGizi(titleGizi: "Yodium", definisiGizi: "Pada ibu hamil, Yodium berguna untuk memproduksi hormon tiroid yang berpengaruh pada perkembangan otak dan organ tubuh janin (saraf), sistem pencernaan, mengendalikan kontraksi otot dan mengatur suhu tubuh.")
 
let Zinc=ZatGizi(titleGizi: "Zinc", definisiGizi: "Pada ibu hamil, Zinc berguna untuk pembentukan DNA pada janin, mempermudah metabolisme tubuh, serta menstabilkan hormon si Ibu sehingga menjaga pertumbuhan otak dan penglihatan janin nantinya.")
 
let Selenium=ZatGizi(titleGizi: "Selenium", definisiGizi: "Pada ibu hamil, Selenium berguna untuk menurunkan resiko ibu terkena pre-eklampsia, serta menyeimbangkan hormon estrogen pada Ibu.")
 
let Mangan=ZatGizi(titleGizi: "Mangan", definisiGizi: "Pada ibu hamil, Mangan berguna untuk membentuk tulang dan jaringan ikat, serta menjamin fungsi saraf yang baik pada janin,. Selain itu, mangan juga penting dalam metabolisme lemak dan karbohidrat, serta penyerapan kalsium dan regulasi gula dalam darah.")

// Isi Bahan Makanan
let Pisang=BahanMakanan(namaBahan: "Pisang", tipeBahan: "Buah", gambarBahan: "Pisang", countMenuPilihanBahan: 2, definisiBahan: "Ada beragam manfaat pisang untuk ibu hamil yang sayang untuk dilewatkan, mulai dari mengatasi sembelit hingga meredakan mual dan muntah di awal kehamilan. Tak hanya baik untuk ibu hamil, kandungan nutrisi di dalam pisang juga dapat menunjang pertumbuhan janin.", arrOfZatGizi: [JenisZatGizi.VitaminB6,JenisZatGizi.VitaminC],arrOfResep: [NuggetPisangUbi,BananaCakeCinnamon])
 
let Alpukat=BahanMakanan(namaBahan: "Alpukat", tipeBahan: "Buah", gambarBahan: "Alpukat", countMenuPilihanBahan: 2, definisiBahan: "Alpukat mengandung lemak tak jenuh tunggal  yang membantu menurunkan kolesterol sembari memasok tubuh dengan senyawa penting untuk otak, mata, sistem saraf, dan jaringan lemak bayi yang sedang berkembang. Alpukat kaya kalium, vitamin B, serat, dan antioksidan. Ibu hamil dapat memperoleh manfaat dari konsumsi rutin alpukat dan makanan berlemak nabati lainnya.", arrOfZatGizi: [JenisZatGizi.VitaminB6,JenisZatGizi.VitaminB9,JenisZatGizi.VitaminC,JenisZatGizi.VitaminK],arrOfResep: [AlpukatKocokMilo,EsAlpukatKelapaMudaNangka])
 
let Jeruk=BahanMakanan(namaBahan: "Jeruk", tipeBahan: "Buah", gambarBahan: "Jeruk", countMenuPilihanBahan: 2, definisiBahan: "Jeruk merupakan salah satu buah yang kaya akan vitamin C. Di Indonesia, Ibu hamil dapat menemukan beragam jenis jeruk, mulai dari jeruk nipis, lemon, sampai jeruk Bali. Selain banyak jenisnya, jeruk pun tidak mengenal musim, sehingga Ibu Hamil dapat mengonsumsinya kapan saja.", arrOfZatGizi: [JenisZatGizi.VitaminC,JenisZatGizi.VitaminB9],arrOfResep: [JusTomatWortelJeruk,EsJerukLemon])
 
let Mangga=BahanMakanan(namaBahan: "Alpukat", tipeBahan: "Buah", gambarBahan: "Mangga", countMenuPilihanBahan: 2, definisiBahan: "Mangga termasuk buah yang tinggi serat, sehingga dapat mencegah sembelit dan melancarkan saluran cerna pada ibu hamil. Serat juga dapat membuat ibu kenyang lebih lama, sehingga mencegah ibu hamil makan berlebih. Mangga juga dapat mencegah sakit yang membahayakan ibu hamil.", arrOfZatGizi: [JenisZatGizi.VitaminC,JenisZatGizi.VitaminA],arrOfResep: [MangoThai,RujakManggaMuda])
 
let Jagung=BahanMakanan(namaBahan: "Jagung", tipeBahan: "Buah", gambarBahan: "Jagung", countMenuPilihanBahan: 2, definisiBahan: "Jagung mengandung vitamin B9 (folat) dan zat besi yang berperan dalam produksi sel darah merah, sehingga baik untuk mendukung perkembangan janin serta mencegah anemia pada ibu hamil.", arrOfZatGizi: [JenisZatGizi.VitaminB9,JenisZatGizi.VitaminB3,JenisZatGizi.VitaminB6,JenisZatGizi.Fosfor,JenisZatGizi.Magnesium,JenisZatGizi.Zinc,JenisZatGizi.Mangan],arrOfResep: [SupJagungWortelTelur,TumisBuncisJagungManis])
 
//=============================================================================
//hewani
let DagingSapi=BahanMakanan(namaBahan: "Daging Sapi", tipeBahan: "Hewani", gambarBahan: "DagingSapi", countMenuPilihanBahan: 2, definisiBahan: "Bagi ibu hamil, mengonsumsi daging sapi dibolehkan apalagi jika memiliki kecenderungan kurang darah atau anemia karena daging sapi juga kaya zat besi. Ibu hamil bisa memilih bagian daging sapi yang tidak banyak lemak atau lean meat seperti bagian khas dalam atau istilahnya tenderloin.", arrOfZatGizi: [JenisZatGizi.VitaminB12,JenisZatGizi.Protein,JenisZatGizi.VitaminC,JenisZatGizi.VitaminB6,JenisZatGizi.Kalsium,JenisZatGizi.Magnesium,JenisZatGizi.ZatBesi],arrOfResep: [CahTomatSapiLadaHitam,SupSayurDaging])
 
let DagingAyam=BahanMakanan(namaBahan: "Daging Ayam", tipeBahan: "Hewani", gambarBahan: "DagingAyam", countMenuPilihanBahan: 2, definisiBahan: "Ayam adalah sumber makanan yang sangat bergizi dengan kandungan protein dan 9 asam amino esensial. Kedua kandungan ini merupakan bahan dasar utama pembangun otot. Daging ayam juga memiliki kandungan lemak yang rendah dan tidak secara signifikan menyebabkan obesitas.", arrOfZatGizi: [JenisZatGizi.VitaminB6,JenisZatGizi.Protein,JenisZatGizi.VitaminC,JenisZatGizi.VitaminB12,JenisZatGizi.Magnesium,JenisZatGizi.ZatBesi],arrOfResep: [SotoSayurAyam,AyamTeriyaki])
 
let Salmon=BahanMakanan(namaBahan: "Salmon", tipeBahan: "Hewani", gambarBahan: "Salmon", countMenuPilihanBahan: 2, definisiBahan: "Salmon mengandung protein yang cukup banyak dan hal ini bisa dimanfaatkan oleh para ibu hamil dan menjadikannya sumber energi. Terutama jika ada banyak aktivitas yang dilakukan dalam sehari-hari, pastinya energi yang dibutuhkan pun harus banyak pula.Kandungan protein pada jenis ikan ini bisa mengontrol jumlah hormon di dalam tubuh supaya tidak semakin meningkat.", arrOfZatGizi: [JenisZatGizi.VitaminB12,JenisZatGizi.Protein,JenisZatGizi.VitaminC,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminC],arrOfResep: [SalmonTeriyaki,SopIkanSalmon])
 
let Susu=BahanMakanan(namaBahan: "Susu", tipeBahan: "Hewani", gambarBahan: "Susu", countMenuPilihanBahan: 2, definisiBahan: "Ibu hamil diwajibkan minum susu selama proses mengandung sang jabang bayi. Oleh karenanya diperlukan susu yang berkualitas untuk bisa memenuhi kualitas gizi terbaik. Salah satu rekomendasi susu adalah produk yang yang telah dipasteurisasi. Artinya, susu akan dipanaskan pada suhu yang tinggi untuk menghancurkan mikroba di dalamnya sehingga lebih aman bagimu dan janin.", arrOfZatGizi: [JenisZatGizi.Protein,JenisZatGizi.VitaminA,JenisZatGizi.VitaminB1,JenisZatGizi.VitaminB2,JenisZatGizi.VitaminB3,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminB9,JenisZatGizi.VitaminB12,JenisZatGizi.VitaminC,JenisZatGizi.VitaminD,JenisZatGizi.VitaminE,JenisZatGizi.Kalsium,JenisZatGizi.Fosfor,JenisZatGizi.Magnesium],arrOfResep: [SusuKurma,BananaChocoMilkSmoothies])
 
let Telur=BahanMakanan(namaBahan: "Telur", tipeBahan: "Hewani", gambarBahan: "telur", countMenuPilihanBahan: 2, definisiBahan: "Telur adalah sumber protein dan kolin yang sangat baik untuk kesehatan ibu hamil dan tumbuh kembang janin. Tidak hanya itu, telur juga mengandung beragam nutrisi penting lainnya, seperti lemak, asam folat, selenium, fosfor, zinc, kalsium, serta vitamin A, B2, B5, B6, B12, D, E, dan K.", arrOfZatGizi: [JenisZatGizi.Protein,JenisZatGizi.VitaminA,JenisZatGizi.VitaminB2,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminD,JenisZatGizi.VitaminE,JenisZatGizi.VitaminK,JenisZatGizi.Kalsium,JenisZatGizi.Fosfor,JenisZatGizi.Zinc,JenisZatGizi.Selenium],arrOfResep: [TelurDadarBalado,TumisSawiTelurTomat])
 
//=============================================================================
 
let Buncis=BahanMakanan(namaBahan: "Buncis", tipeBahan: "Kacang", gambarBahan: "Buncis", countMenuPilihanBahan: 2, definisiBahan: "Buncis mengandung asam folat yang bermanfaat untuk meningkatkan pertumbuhan janin. Dengan mengonsumsi buncis dapat membuat janin yang akan lahir sempurna tanpa adanya cacat.", arrOfZatGizi: [JenisZatGizi.VitaminB9,JenisZatGizi.Protein,JenisZatGizi.VitaminB1,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminE,JenisZatGizi.VitaminK,JenisZatGizi.Fosfor,JenisZatGizi.Magnesium,JenisZatGizi.ZatBesi,JenisZatGizi.Zinc,JenisZatGizi.Selenium,JenisZatGizi.Mangan],arrOfResep: [BuncisCumiPeteTumis,TumisTempeBuncisKecap])
 
let KacangTanah=BahanMakanan(namaBahan: "Kacang Tanah", tipeBahan: "Kacang", gambarBahan: "KacangTanah", countMenuPilihanBahan: 2, definisiBahan: "Kacang tanah baik untuk ibu hamil karena memiliki kandungan asam folat. Ini merupakan nutrisi yang sangat penting untuk mencegah cacat tabung saraf pada janin. Oleh karena itu, apabila ibu merasa sering ngemil, kacang tanah merupakan salah satu pilihan yang tepat.", arrOfZatGizi: [JenisZatGizi.VitaminB9,JenisZatGizi.Protein,JenisZatGizi.Kalsium,JenisZatGizi.ZatBesi],arrOfResep: [SayurAsam,BakpaoIsiKacangTanah])
 
let KacangPolong=BahanMakanan(namaBahan: "Kacang Polong", tipeBahan: "Kacang", gambarBahan: "KacangPolong", countMenuPilihanBahan: 2, definisiBahan: "Kacang polong memiliki kandungan vitamin dan nutrisi yang sangat luar biasa. Kandungannya meliputi, Vitamin A, vitamin K, vitamin B kompleks, magnesium, vitamin C, dan serat semua ada pada kacang polong.", arrOfZatGizi: [JenisZatGizi.Protein,JenisZatGizi.VitaminB9,JenisZatGizi.Kalsium,JenisZatGizi.ZatBesi],arrOfResep: [CreamSoupAyamJagungPolong,SeblakPastaSpiral])
 
let KacangKedelai=BahanMakanan(namaBahan: "Kacang Kedelai", tipeBahan: "Kacang", gambarBahan: "KacangKedelai", countMenuPilihanBahan: 2, definisiBahan: "Pada kacang kedelai ternyata ada kandungan asam folat yang sangat tinggi. Asam folat ini sangat dibutuhkan ibu hamil untuk membantu perkembangan janin dalam kandungannya bisa berkembang secara optimal. Bahkan asam folat ini sudah harus dipenuhi kebutuhannya selama masa persiapan hamil.", arrOfZatGizi: [JenisZatGizi.Kalsium,JenisZatGizi.Protein,JenisZatGizi.VitaminB9,JenisZatGizi.ZatBesi],arrOfResep: [SusuKedelai,BayamTahu])
 
//=============================================================================
 
let SayurBayam=BahanMakanan(namaBahan: "Sayur Bayam", tipeBahan: "Sayur", gambarBahan: "Bayam", countMenuPilihanBahan: 2, definisiBahan: "Ada beragam manfaat bayam untuk ibu hamil, mulai dari meningkatkan imunitas tubuh hingga mencegah bayi terlahir dalam kondisi cacat. Hal ini karena bayam mengandung nutrisi, seperti vitamin A, vitamin C, vitamin K, protein, serat, asam folat, zat besi, dan kalsium.", arrOfZatGizi: [JenisZatGizi.VitaminA,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminB9,JenisZatGizi.VitaminC,JenisZatGizi.VitaminE,JenisZatGizi.VitaminK,JenisZatGizi.Kalsium,JenisZatGizi.Magnesium,JenisZatGizi.ZatBesi],arrOfResep: [BayamBeningJagung,Japchae])
 
let SayurBrokoli=BahanMakanan(namaBahan: "Sayur Brokoli", tipeBahan: "Sayur", gambarBahan: "Brokoli", countMenuPilihanBahan: 2, definisiBahan: "Manfaat brokoli untuk ibu hamil berasal dari nutrisi yang terkandung di dalamnya. Brokoli mengandung banyak serat, vitamin A, vitamin C, vitamin K, zat besi, folat, kalium, dan kalsium. Nutrisi ini tentunya sangat baik untuk ibu hamil dan janin yang dikandungnya.", arrOfZatGizi: [JenisZatGizi.Fosfor,JenisZatGizi.Protein,JenisZatGizi.VitaminC,JenisZatGizi.VitaminB9,JenisZatGizi.VitaminC,JenisZatGizi.VitaminK,JenisZatGizi.ZatBesi,JenisZatGizi.Mangan],arrOfResep: [BrokoliCahWortel,BrokoliJamurSopKental])
 
let SayurWortel=BahanMakanan(namaBahan: "Sayur Wortel", tipeBahan: "Sayur", gambarBahan: "Wortel", countMenuPilihanBahan: 2, definisiBahan: "Wortel mengandung mangan, yang merupakan mineral penting dalam proses pembentukan tulang dan tulang rawan janin. Sayuran berwarna oranye ini juga mengandung kalsium, yang baik untuk menjaga kekuatan tulang dan gigi Bunda.", arrOfZatGizi: [JenisZatGizi.VitaminA,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminK],arrOfResep: [BrokoliCahWortel, KariKentangWortel])
 
let Ubi=BahanMakanan(namaBahan: "Ubi", tipeBahan: "Umbi", gambarBahan: "Ubi", countMenuPilihanBahan: 2, definisiBahan: "Ubi jalar dianggap aman untuk dikonsumsi saat hamil dan mereka kaya akan vitamin A dan C, dan serat. Namun, wanita dengan atau mereka yang memiliki riwayat penyakit ginjal kronis harus menghindari makan ubi, karena makanan ini mengandung oksalat dalam jumlah tinggi yang dapat meningkatkan risiko batu ginjal.", arrOfZatGizi: [JenisZatGizi.ZatBesi,JenisZatGizi.Protein,JenisZatGizi.VitaminA,JenisZatGizi.VitaminB6,JenisZatGizi.VitaminC,JenisZatGizi.Mangan],arrOfResep: [CemilanBolaUbiUngu, SopUbiMakassar])
 


//isi Resep Makanan
let BayamBeningJagung=ResepMakanan(titleMakanan: "Bayam Bening Jagung", daftarBahanMasakan: "1 ikat bayam, 1 buah wortel ukuran kecil, 1 buah jagung ukuran kecil ,10 buah bawang putih, Garam secukupnya, Minyak untuk menggoreng bawang putih, Air", caraMasakan: "Petik bayam, Cuci bersih bayam, wortel, dan jagung dengan air mengalir. ,Potong wortel dan jagung sesuai selera. ,...........", gambarMasakan: "BayamBeningJagung")
 
let Japchae=ResepMakanan(titleMakanan: "Japchae", daftarBahanMasakan: "1 papan bihun jagung, Bayam yang sudah disiangi secukupnya, 1,5 genggam jamur kuping, 2 butir telur, Kecap asin secukupnya, Kecap manis secukupnya, Minyak wijen secukupnya, Sedikit garam dan ladaang merah iris, siung bawang putih iris, Gula pasir secukupnya, Garam sesuai selera", caraMasakan: "Siapkan bayam, tahu, bawang iris dan cabe iris. ,Cuci bersih bayam dan tahu lalu potong, Panaskan air dalam panci lalu aduk gula dan garam sampai mendidih. ,Saat sudah mendidih, masukan bayam lalu tahu dan aduk merata. Koreksi rasa dengan menambahkan gula atau garam sesuai selera. ,Masukkan bawang merah, bawang putih, dan cabe yang telah diiris, Tunggu hingga bawang layu lalu angkat dan sajikan.", gambarMasakan: "Japchae")
 
//=============================================================================
//isi Resep Makanan Sayur 2
let BrokoliCahWortel=ResepMakanan(titleMakanan: "Brokoli Cah Wortel", daftarBahanMasakan: "1 ikat bayam, 1 buah wortel ukuran kecil, 1 buah jagung ukuran kecil,10 buah bawang putih, Garam secukupnya, Minyak untuk menggoreng bawang putih, Air", caraMasakan: "Petik bayam, Cuci bersih bayam, wortel, dan jagung dengan air mengalir. ,Potong wortel dan jagung sesuai selera. ,Rebus air sampai mendidih, masukan jagung dan wortel, lalu rebus hingga matang. ,Masukkan bayam ke dalam rebusan jagung dan wortel lalu aduk rata. Rebus bayam kira-kira 2-3 menitan. ,Beri garam sambil di tes rasanya hingga kira-kira sudah sesuai dengan selera lalu matikan kompor. ,Iris tipis bawang putih lalu goreng di minyak panas sampai kecoklatan lalu tiriskan. ,Ibu dapat memilih untuk langsung memasukkan bawang putih goreng ke dalam kuah sayur atau ditumbuk halus dulu baru dituang. ,Sayur bayam bening pun jadi.", gambarMasakan: "BrokoliCahWortel")
 
let BrokoliJamurSopKental=ResepMakanan(titleMakanan: "Brokoli Jamur Sop Kental", daftarBahanMasakan: "2 bongkol brokoli, 5 butir jamur champignon, 1/2 butir bawang bombay, 3 siung bawang putih, 1 butir telur kocok (hanya pakai 2 sdm), 1 Sdm munjung tepung maizena larutkan dengan 2 sdm air, 1-2 Sdm saus tiram, 1 sdt minyak wijen, 1/2 sdt sea salt / kaldu jamur ,Sejumput gula pasir, Air secukupnya", caraMasakan: "Potong-potong brokoli lalu cuci bersih, Rebus air hingga mendidih, Rebus brokoli sebentar, angkat, tiriskan, lalu siram air dingin. Sisihkan. ,Tumis bawang bombay dan bawang putih hingga layu. Masukkan jamur, dan tumis sebentaran saja. Tambah air secukupnya lalu masukkan garam laut, saus tiram, minyak wijen, dan gula. Aduk rata lalu di icip. ,Kalau Sudah pas, masak hingga harum mendidih. ,Sesudah mendidih, masukkan brokoli. Aduk sebentar dan masukkan 2-3 sdm telur kocok sambil diaduk cepat hingga telur berbentuk serabut. ,Tuang juga larutan maizena dan aduk hingga mendidih mengental.", gambarMasakan: "BrokoliJamurSopKental")
 
//=============================================================================
//isi Resep Makanan Sayur 3
let SupJagungWortel=ResepMakanan(titleMakanan: "Sup Jagung Wortel", daftarBahanMasakan: "2 Buah Bawang Putih di iris , 1/2 Buah Bawang Bombay di potong dadu, 1 Buah Jagung diserut, 1/2 Buah Wortel di potong dadu kecil, 700 ml Air Putih, 2 Butir Telur di kocok lepas ,2 sdm Blue Band untuk tumis, Secukupnya Totole atau Kaldu lainnya ,2 sdm Maizena dilarutkan di air ,Garam secukupnya ,Seledri secukupnya", caraMasakan: "Lelehkan blueband diatas panci lalu tumis bawang bombay dan wortel hingga layu ,Masukkan sedikit air dan jagung lalu korek hingga setengah matang ,Setelah Jagung Mulai matang, tambahkan air perlahan hingga jagung benar-benar matang ,Blender menggunakan hand blender agar tekstur hancur sedikit. ,Masukkan telur sedikit dan aduk cepat, masukkan lagi telurnya hingga habis. ,Masukkan totole, garam, Merica, dan cicipi hingga pas di lidah. ,Masukkan seledri, aduk rata, dan sajikan.", gambarMasakan: "SopJagungWortel")
 
let KariKentangWortel=ResepMakanan(titleMakanan: "Kari kentang Wortel", daftarBahanMasakan: "3 buah kentang, potong dadu ,2 buah wortel, potong kotak ,2 siung bawang putih, cincang halus ,1/2 buah bombay, iris kotak ,300-400 ml air ,1-2 sdm pasta kari ,1 sdm pasta cabe,65 ml santan instant ,1 sdt garam ,2 sdt gula ,1 sdt merica ,1/2 sdt kaldu bubuk ,batang daun bawang bagian hijau , 1 sdt maizena larutkan dengan 1 sdm air", caraMasakan: "Petik bayam, Cuci bersih bayam, wortel, dan jagung dengan air mengalir. ,Potong wortel dan jagung sesuai selera. ,Rebus air sampai mendidih, masukan jagung dan wortel, lalu rebus hingga matang. ,Masukkan bayam ke dalam rebusan jagung dan wortel lalu aduk rata. Rebus bayam kira-kira 2-3 menitan. ,Beri garam sambil di tes rasanya hingga kira-kira sudah sesuai dengan selera lalu matikan kompor. ,Iris tipis bawang putih lalu goreng di minyak panas sampai kecoklatan lalu tiriskan. ,Ibu dapat memilih untuk langsung memasukkan bawang putih goreng ke dalam kuah sayur atau ditumbuk halus dulu baru dituang. ,Sayur bayam bening pun jadi.", gambarMasakan: "KariKentangWortel")
//=============================================================================
//isi Resep Makanan Ubi 1
 
let CemilanBolaUbiUngu=ResepMakanan(titleMakanan: "Cemilan Bola Ubi Ungu", daftarBahanMasakan: "Bahan utama, 500 gr ubi ungu, kukus, 2 sdm gula, 2 sdm margarin, 1/2 sdt garam, 7 sdm tepung terigu, Secukupnya keju oles / mozarella untuk isian, Bahan Pelapis, 3 sdm tepung terigu, 1 butir telur, Secukupnya air, Secukupnya tepung roti", caraMasakan: "Siapkan bahan dan ubi yang sudah dikukus, Lumatkan ubi sampai halus, lalu campurkan sisa bahan utama (kecuali tepung), Setelah diaduk sampai rata, campurkan tepung. ,Bentuk adonan menjadi bulat sesuai selera dengan isian sesuai selera juga (bisa cokelat, keju, atau topping lainnya) ,Pindah ke bahan pelapis. Campurkan tepung, telur dan air sedikit demi sedikit sampai kekentalan normal dan sedikit lebih cair. Diusahakan jangan terlalu kental. ,Masukkan ubi ke bahan pelapis lalu balur dengan tepung roti. ,Panaskan minyak, dan goreng bola ubi sampai warna nya coklat keemasan.", gambarMasakan: "CamilanBolaUbiUngu")
 
let SopUbiMakassar=ResepMakanan(titleMakanan: "Sop Ubi Maskassar", daftarBahanMasakan: "Singkong, potong sesuai selera, 1 keping bihun jagung/soun, 2 keping mie kuning, 2 genggam tauge ,1kg Konro ayam ,2-3 liter air kuah, Bumbu halus, 7 siung bawang merah, 7 siung bawang putih, uk.kecil ,1/2 sdt merica ,1/2 sdt ketumbar ,1/2 sdt jintan ,2 butir kemiri, Bumbu cemplung ,1 buah bunga lawang ,1buah kapulaga ,3 buah cengkeh ,1 ruas jahe, geprek ,1 batang kecil kayu manis ,secukupnya Garam, secukupnya Kaldu bubuk", caraMasakan: "Masukkan konro ayam ke dalam air mendidih, rebus sebentar dan angkat. (Tujuannya agar kotoran dalam ayam serta aroma khas ayam hilang, air rebusan pertama dibuang) ,Tumis bumbu halus, masukkan ke dalam kuah sop direbusan kedua. ,Beri bumbu cemplung dan masak hingga bumbu meresap lalu koreksi rasa. ,Kukus singkong lalu goreng hingga kecoklatan. Soun dan mie rendam dengan air panas lalu di bilas air dingin. Taugenya direbus sebentar.Gabungkan sop dengan ubi, soun, mie, dan tauge untuk disajikan. Jika ingin menggunakan pelengkap, bisa menambahkan jeruk nipis, kecap, cabai rawit, daun bawang, daun sup, bawang goreng, kacang goreng, dan telur rebus.", gambarMasakan: "SopUbiMakassar")
 
//=============================================================================
//buah
 
let NuggetPisangUbi=ResepMakanan(titleMakanan: "Nugget Pisang Ubi", daftarBahanMasakan: "200 gr pisang uli ,100 gr ubi kukus ,4 sdm tepung roti ,Secukupnya tepung roti untuk pelapis ,Secukupnya minyak goreng", caraMasakan: "Lumatkan ubi dan pisang (kasar saja, jangan sampai halus. ,Tambahkan tepung roti, lalu aduk rata. ,Siapkan lagi tepung roti untuk pelapis di piring. ,Bentuk adonan menjadi bentuk nugget atau sesuai selera kemudian dibalur di tepung roti. ,Panaskan minyak, goreng hingga berwarna coklat keemasan (satu kali balik saja agar tidak terlalu banyak menyerap minyak)", gambarMasakan: "NuggetPisangUbi")
 
let BananaCakeCinnamon=ResepMakanan(titleMakanan: "Banana Cake Cinnamon", daftarBahanMasakan: "200 gr tepung kunci ,3 buah pisang baranang hancurkan (tinggi banget gizinya),75 gr gula ,150 gr margarin lelehkan ,5 sdm susu bubuk hamil ,50 gr butter lelehkan ,3 butir telur ,1/2 sdm baking soda ,1 sdm bubuk kayu manis", caraMasakan: "Ayak tepung lalu campurkan dengan susu dan baking soda. Aduk rata. ,Masukkan telur, pisang, gula, dan bubuk kayu manis (cinnamon). ,Aduk dengan whisk hingga rata. ,Panaskan oven 10 menit 150 derajat. ,Panggang selama 30-45 menit lalu tes kematangan dengan ditusuk.",gambarMasakan: "BananaCakeCinammon")
 
//=============================================================================
// buah 2
let AlpukatKocokMilo=ResepMakanan(titleMakanan: "Alpukat Kocok Milo", daftarBahanMasakan: "1/2 butir Alpukat, Susu uht plain, 1/2 sachet Milo ,Frisian Flag Kental Manis Gold", caraMasakan: "Alpukat disisir kasar lalu disiapkan di gelas atau mangkuk ,Tambahkan susu secukupnya ,Taburi dengan milo dan beri kental manis sesuai selera.",gambarMasakan: "AlpukatCoklatMilo")
 
let EsAlpukatKelapaMudaNangka=ResepMakanan(titleMakanan: "Es Alpukat Kelapa Muda Nangka", daftarBahanMasakan: "1 Buah Kelapa Muda ,1 Buah Alpukat ,secukupnya Nangka ,1 liter Susu Full Cream ,5 sdm Frisian Flag Kental Manis Gold ,secukupnya Es Batu", caraMasakan: "Kerok daging kelapa muda, kupas alpukat, dan potong nangka bentuk dadu. ,Masukkan semua bahan ke dalam wadah, tambahkan susu full cream, dan kental manis, lalu aduk rata. ,Tambahkan es batu sesuai selera.", gambarMasakan: "EsAlpukatKelapaMudaNangka")
 
//=============================================================================
// buah 3
let JusTomatWortelJeruk=ResepMakanan(titleMakanan: "Jus Tomat Wortel Jeruk", daftarBahanMasakan: "buah tomat ,1 buah wortel ,2 buah jeruk ,secukupnya Air", caraMasakan: "Potong tomat dan wortel ,Peras Jeruk ,Masukkan dalam blender dan tambah sedikit air ,Saring ampas bila tidak menyukai ampas", gambarMasakan: "JusTomatWortelJeruk")
 
let EsJerukLemon=ResepMakanan(titleMakanan: "Es Jeruk Lemon", daftarBahanMasakan: "3 buah jeruk madu ,2 slice lemon ,2 sdt chia seed ,1/2 gelas air matang ,Secukupnya es batu", caraMasakan: "Rendam chia seed dalam air hingga mengembang (30 menitan) ,Peras jeruk dan lemonnya lalu diaduk ,Tuangkan chia seed dan air secukupnya lalu diaduk lagi ,Berikan es batu biar segar dan gula bila tidak terlalu suka asam.", gambarMasakan: "EsJerukLemon")
 
//=============================================================================
// buah 4
let MangoThai=ResepMakanan(titleMakanan: "Mango Thai", daftarBahanMasakan: "3 Buah Mangga Gedong Gicu ,3 sdm Gula ,secukupnya Es batu ,100 ml air dingin ,Bahan Wipped cream ,1 Susu Dancow Putih ,Secukupnya Es Batu", caraMasakan: "Jus buah mangga tapi jangan terlalu encer ,Buat whipped cream dengan mencampurkan SKM, susu dancow, SP, dan es batu. Kemudian mixer hingga kental melekat dan masukkan ke plastik. ,Masukkan jus mangga tadi setengah gelas lalu tambahkan whipped cream sesuai selera dan beri potongan mangga diatasnya.", gambarMasakan: "MangoThai")
 
let RujakManggaMuda=ResepMakanan(titleMakanan: "Rujak Mangga Muda", daftarBahanMasakan: "1 buah mangga muda ,1 buah timun ukuran kecil ,2 sdm kacang goreng ,4 butir cabe rawit ,4 sdm gula merah ,1/2 sdm gula pasir ,20 cc air mineral ,secukupnya Garam", caraMasakan: "Kupas kulit mangga, iris tipis, rendam dengan air garam (agar tidak asam kecut), tiriskan dan bilas dengan air bersih. ,Kupas kulit timun, iris tipis, cuci bersih. ,Buat bumbu rujak dengan mengulek kacang goreng dan cabe rawit bersama dengan gula merah, gula pasir, dan garam secukupnya. Tambahkan sedikit air mineral lalu koreksi rasa. ,Sajikan mangga dan timun dengan bumbu rujak.", gambarMasakan: "RujakManggaMuda")
 
 
 
//=============================================================================
// buah 5
let SupJagungWortelTelur=ResepMakanan(titleMakanan: "Sup Jagung Wortel Telur", daftarBahanMasakan: "3 Buah Mangga Gedong Gicu ,3 sdm Gula ,secukupnya Es batu ,100 ml air dingin ,Bahan Wipped cream ,1 Susu Dancow Putih ,Secukupnya Es Batu", caraMasakan: "Lelehkan blueband diatas panci lalu tumis bawang bombay dan wortel hingga layu ,Masukkan sedikit air dan jagung lalu korek hingga setengah matang ,Setelah Jagung Mulai matang, tambahkan air perlahan hingga jagung benar-benar matang ,Blender menggunakan hand blender agar tekstur hancur sedikit. ,Masukkan telur sedikit dan aduk cepat, masukkan lagi telurnya hingga habis. ,Masukkan totole, garam, Merica, dan cicipi hingga pas di lidah. ,Masukkan seledri, aduk rata, dan sajikan.",gambarMasakan: "SupJagungWortelTelur")
 
let TumisBuncisJagungManis=ResepMakanan(titleMakanan: "Tumis Buncis Jagung Manis", daftarBahanMasakan: "1/4 kg Buncis, iris serong ,1 buah Jagung Manis, dipipil ,5 siung Bawang merah, iris halus ,5 siung Bawang putih, iris halus ,1 buah Bawang bombay, iris kasar ,3 lembar Daun bawang, iris memanjang ,1 buah Tomat, iris kasar ,5 buah Cabe keriting merah, iris memanjang ,5 buah Cabe hijau, iris memanjang ,1 bungkus Saus tiram (saori) ,1 sdm Gula putih ,1/2 sdt Merica bubuk ,Secukupnya Garam ,Secukupnya Minyak goreng (untuk menumis)", caraMasakan: "Cuci bersih terdahulu buncis dan jagung (sudah di kupas). Buncis iris serong, pipil jagung. ,Tumis bawang merah, bawang putih, bawang bombai sampai harum. ,Tambahkan saus tiram, gula putih, lada bubuk dan garam. ,Masukan cabe keriting dan cabe hijau. Kemudian masukan buncis dan jagung. ,Setelah setengah matang, masukan tomat dan daun bawang, sampai matang. ",gambarMasakan: "TumisBuncisJagungManis")
 
//=============================================================================
// Hewan 1
 
let CahTomatSapiLadaHitam=ResepMakanan(titleMakanan: "Cah Tomat Sapi Lada Hitam", daftarBahanMasakan: "250 gram roastbeef, iris tipis-tipis, 5 siung bawang putih, potong tipis, 1 tangkai daun bawang, potong tebal menyerong, 2 tomat, iris kotak, 3 sdm saos tiram, Secukupnya lada hitam ,Secukupnya bawang bubuk,Secukupnya kaldu sapi ,Secukupnya air", caraMasakan: "Iris tipis daging sapi lalu beri saos tiram dan bawang bubuk. Campur sampai merata dan diamkan selama 10 menit. ,Tumis bawang putih dan cabai, setelah harum masukkan daging. ,Tambahkan air secukupnya dan masak sekitar 20-25 menit sampai daging benar-benar matang. ,Setelah dagingnya matang, masukkan kecap, kaldu sapi, dan lada hitam lalu tumis sebentar. ,Masukkan tomat dan daun bawang dan masak sekitar 10 menit. ,Aduk-aduk sampai mencampur lalu koreksi rasa, jika kurang asin tambahkan kaldu sapi.",gambarMasakan: "CahTomatSapiLadaHitam")
 
let SupSayurDaging=ResepMakanan(titleMakanan: "Sup Sayur Daging", daftarBahanMasakan: "1/2 kilo daging dan tulang sapi ,1 batang daun bawang ,1 batang seledri ,4 siung bawang merah ,4 siung bawang putih ,1 sdt jahe yang dihaluskan ,1 sdt lengkuas yang dihaluskan ,seujung sendok teh kunyit yang dihaluskan ,4 biji merica ,4 buah ketumbar ,secukupnya jinten ,2 biji cabe jawa ,2 buah kapol ,1 buah kulit manis ,secukupnya adas manis ,2 biji pekak ,1/2 buah pala ,2 lbr daun jeruk ,3 biji cengkeh ,1 bungkus royco ,secukupnya garam ,secukupnya air ,1 buah kentang ,1 buah wortel ,1 buah brokoli", caraMasakan: "Rebus daging dan tulang dengan air lalu tambahkan kulit manis dan buah pala. ,Buang air rebusan yang menghitam (lemak yang menggumpal) hingga air rebusan terlihat lebih bening. ,Setelah daging empuk, masukkan kentang dan wortel dan rebus hingga sayuran matang. ,Untuk bumbu halus, giling merica, ketumbar, jinten, cabe jawa, kapol, Adas manis, pekak, dan cengkeh ,Tumis bawang merah, bawang putih, dan daun jeruk hingga harum. Lalu masukkan jahe, lengkuas, dan kunyit yang telah dihaluskan. Aduk hingga semua bahan tercampir. Terakhir masukkan bumbu halus, daun bawang dan seledri, masak hingga semua bahan tercampur rata dan aroma harum. ,Campurkan tumisan bumbu ke dalam air rebusan daging dan sayuran, tambahkan brokoli, royco,dan garam. Masak selama 5 menit saja lalu sajikan. ",gambarMasakan: "SopSayurDaging")
//=============================================================================
// Hewan 2

let SotoSayurAyam=ResepMakanan(titleMakanan: "Soto Sayur Ayam", daftarBahanMasakan: "1/2 ekor ayam potong kecil, 5 tomat hijau, 1 kentang besar, 2 wortel, 3 tangkai daun bawang, 4 tangkai seledri, 3 cabai rawit utuh, 3 daun salam, 3 daun jeruk, 2 serai geprek, 1 ruas jahe geprek, 1 ruas lengkuas geprek secukupnya garam secukupnya gula secukupnya merica Bumbu halus, 3 bawang merah,3 bawang putih, 5 cabai rawit (selera), 6 cabai merah keriting, 2 kemiri,1 ruas kunyit", caraMasakan: "1. Rebus ayam terlebih dahulu sebelum digoreng agar memastikan ayam matang sempurna., 2. Giling bumbu (bawang merah, bawang putih, cabai rawit, cabai merah keriting, kemiri, dan kunyit) sampai halus lalu tumis hingga harum lalu masukkan daun salam, daun jeruk, serai, jahe, dan lengkuas. Beri air lalu masak hingga mendidih., 3. Masukkan sayuran, tunggu beberapa menit lalu tuang ayam. Tidak perlu masak ayam lama-lama karena ayam sudah matang., 4. Beri garam, gula dan merica bubuk lalu koreksi rasa sesuai selera.",gambarMasakan: "SotoSayurAyam")
 
let AyamTeriyaki=ResepMakanan(titleMakanan: "Ayam Teriyaki", daftarBahanMasakan: "250 gram fillet ayam, 1 buah cabe merah ,1 buah cabe hijau ,1 buah bawang bombay ,secukupnya penyedap", caraMasakan: "Cuci ayam, lumuri dengan saori saos teriyaki, tunggu 15 menit, Tumis bawang bombay, cabe hijau dan merah sampai harum, Masukan ayam yg sudah di lumuri, Tambahkan penyedap, Koreksi rasa, tunggu hingga matang ",gambarMasakan: "Ayam Teriyaki")
 
//=============================================================================
// Hewan 3
let SalmonTeriyaki=ResepMakanan(titleMakanan: "Salmon Teriyaki", daftarBahanMasakan: "200 gr Wild Salmon ,1 sdt Bawang Merah Giling ,1/2 sdm Bawang Putih Giling ,2 buah Bawang Putih (geprek dan jangan buang kulitnya) ,3 sdm Saos Teriyaki (atau secukupnya) ,Secukupnya margarin untuk menggoreng salmon ,Secukupnya Lada Bubuk ,Secukupnya Garam", caraMasakan: "Cuci Salmon lalu keringkan dengan tissue dapur atau lap bersih. Potong sesuai selera dan marinasi dengan garam dan lada selama kurang lebih 5 menit. ,Masukkan margarin ke dalam wajam, lalu goreng salmon beserta bawang putih geprek dengan api. ,Goreng yang sisi kulitnya dahulu lalu dibolak balik setiap sisinya. ,Tumis bawang giling dengan margarin sisa menggoreng salmon. Masukkan saus teriyaki, garam, dan lada sesuai selera. Tes rasa lalu masukkan salmon yang sudah digoreng. Kemudian aduk rata. ,Boleh disajikan dengan kentang goreng dan sayuran campur (wortel, jagung, dan buncis).",gambarMasakan: "SalmonTeriyaki")
 
let SopIkanSalmon=ResepMakanan(titleMakanan: "Sop Ikan Salmon", daftarBahanMasakan: "100 gr salmon ,1/2 jagung pipil ,1 wortel lokal uk besar ,1/8 brokoli ,1/8 sdt bubuk kunyit ,2 serai ,1 ruas jahe ,1 ruas laos ,1/2 buah perasan lemon ,1 bawang putih ,2 bawang merah ,1 tomat potong dadu ,secukupnya minyak kanola ,secukupnya garam", caraMasakan: "Tumis bawang putih dan bawang merah menggunakan sedikit saja minyak kanola. ,Masukkan wortel tumis sebentar. Tambahkan 1/2-1 liter air ,Masukkan jagung, jahe, serai, laos, masak hingga matang ,Tuang ikan salmon, tomat dan brokoli, masukkan garam, koreksi rasa. ,Setelah dirasa matang, matikan kompor masukkan perasan air lemon.",gambarMasakan: "SopIkanSalmon")
 
 
 
//=============================================================================
// Hewan 4
let SusuKurma=ResepMakanan(titleMakanan: "Susu Kurma", daftarBahanMasakan: "25 buah kurma (sudah kupas biji) ,1 Liter susu plain (bisa pakai yang low-fat) ,1-2 sdm madu ,300 ml Air panas", caraMasakan: "Rendam kurma yang sudah dikupas bijinya dengan air panas selama 20 menit. ,Blender kurma dan air rendamannya hingga halus ,Setelah halus, masukkan susu plain dan lanjut blender hingga benar-benar tercampur dan halus. ,Masukkan madu secukupnya ,Lalu blender lagi hingga halus, bila tidak ingin ada serat bisa disaring terlebih dahulu.", gambarMasakan: "SusuKurma")

let BananaChocoMilkSmoothies=ResepMakanan(titleMakanan: "Banana Choco Milk Smoothies", daftarBahanMasakan: "2 buah pisang matang beku ,2-3 sdm susu ibu hamil rasa coklat ,20 ml air mineral dingin ,Topping : ,1 sdm almond panggang ,1 sdt biji chia ,1 sdt quinoa ,1 buah pisang matang", caraMasakan: "Blender pisang, air, dan susu hingga halus ,Tempatkan diwadah dan hiasi dengan topping ,Topping sebenarnya sepengennya Ibu dan susu pun bisa diganti dengan greek yogurt, susu kedelai, susu almond, atau susu low fat.", gambarMasakan: "BananaChocoMilkSmoothies")
 
//=============================================================================
// Hewan 5
let TelurDadarBalado=ResepMakanan(titleMakanan: "Tahu telur balado", daftarBahanMasakan: "5 tahu, potong dadu ,4 butir telur ,5 buah tomat merah ,cabe rawit sesuai selera, 2 lembar daun bawang ,2 siung bawang putih ,3 siung bawang merah ,1/4 gula jawa ,secukupnya Garam ,Royco rasa ayam sebagai penyedap ,Minyak untuk menumis", caraMasakan: "Goreng tahu dan telur ceplok secara terpisah lalu sisihkan. ,Potong tipis tomatnya, potong juga daun bawang kecil-kecil. ,Ulek semua bumbu (cabai, bawang merah,, dan bawang putih). ,Tumis terlebih dahulu tomat yang Sudah dipotong dan biarkan sampai empuk dan sedikit hancur. ,Kalau Sudah agak lumat, masukkan bumbu halusnya dan gula jawanya. Beri garam dan Royco, lalu masukkan tahu dan telur kemudian aduk sampai sambal merata. Jangan lupa koreksi rasa sesuai selera. ,Terakhir, masukkan irisan daun bawang lalu angkat dan sajikan.", gambarMasakan: "TelurBalado")

let TumisSawiTelurTomat=ResepMakanan(titleMakanan: "Tumis Sawi Telur Tomat", daftarBahanMasakan: "secukupnya Sawi, 1 buah Tomat ,2 butir Telur ,Kaldu non msg ,Lada ,Garam", caraMasakan: "Panaskan sedikit minyak di wajan. Tuang telurnya seperti mau bikin mata sapi. Saat setengah matang, langsung diorak-arik telurnya. ,Beri kaldu bubuk. Oseng-oseng sebentar. ,Masukkan sawi dan tomat yang sudah diiris. Tumis hingga matang. Beri lada dan garam sesuai selera. Hidangkan.",gambarMasakan: "TumisSawiTelurTomat")

//=============================================================================
// Kacang 1
let BuncisCumiPeteTumis=ResepMakanan(titleMakanan: "Buncis Cumi Pete Tumis", daftarBahanMasakan: "500 gram Buncis ,200 gram Cumi Asin ,200 gram Petai ,secukupnya Bawang Putih ,3 sendok makan Minyak Goreng ,secukupnya Garam ,secukupnya Kaldu Ayam Bubuk", caraMasakan: "Bersihkan petai, cuci, dan tiriskan. Petik buncis agak pendek kira-kira 3cm ,Tumis bawang putih, masukkan sotong kering, aduk rata. ,Setelah 5 menit, masukkan petai, masak dengan memberi air sebanyak 500ml, masak sampai sotong dan petai empuk. ,Setelah 15 menit, masukkan buncis dan tumis jangan sampai matang, tapi setengah matang dan kehijauan, beri garam, dan kaldu ayam bubuk. ,Angkat dan sajikan.",gambarMasakan: "BuncisCumiPeteTumis")
let TumisTempeBuncisKecap=ResepMakanan(titleMakanan: "Tumis Tempe Buncis Kecap", daftarBahanMasakan: "papan tempe ,200 gr buncis ,Bumbu iris ,3 siung bawang merah ,1 siung bawang putih ,2 buah cabe merah besar ,2 buah cabe rawit ,1 sdt kaldu jamur ,1/2 sdt garam halus ,2 sdm kecap manis ,1/4 sdt merica bubuk ,1/2 gelas air", caraMasakan: "Potong-potong tempe dan buncis ,Tumis bawang yang Sudah diiris hingga layu, lalu masukkan cabai, tumis hingga wangi ,Masukkan tempe dan buncis, beri garam dan kaldu bubuk, beri air, aduk, dan tutup kurang lebih selama 2-3 menit ,Masukkan kecap, aduk rata, lalu terakhir masukkan lada bubuk dan koreksi rasa.",gambarMasakan: "TumisTempeBuncisKecap")

 
//=============================================================================
// Kacang 2
let SayurAsam=ResepMakanan(titleMakanan: "Sayur Asam (Tanpa Terasi)", daftarBahanMasakan: "1 bungkus sayur asam ,1 sdt asam jawa ,1 genggam kacang tanah ,2 lembar daun salam ,1 batang serai digeprek. ,1 sdt kaldu jamur ,2 sdt gula pasir ,Secukupnya garam ,1 liter air ,Bumbu halus ,5 siung bawang merah ,2 siung bawang putih ,5 buah cabai merah", caraMasakan: "Potong semua bahan sayuran sesuai selera, lalu dicuci bersih. ,Ulek kasar bumbu halus (bawang merah, bawang putih, dan cabai merah). Boleh menambahkan sedikit garam pada bumbu halus tetapi kurangi garam saat masak nanti. ,Masak air hingga mendidih. Setelah mendidih, masukan sayur, masukan bumbu halus, masukkan daun salam dan serai. Aduk-aduk sayurannya. ,Kemudian tambahkan asam Jawa. Masak sayur hingga mulai empuk , Setelah sayuran mulai empuk, masukkan kaldu jamur (boleh diganti dengan kaldu bubuk), gula, dan garam. Koreksi rasa lalu lanjut masak sayur hingga empuk.",gambarMasakan: "SayurAsam(TanpaTerasi)")

let BakpaoIsiKacangTanah=ResepMakanan(titleMakanan: "Bakpao Isi Kacang Tanah", daftarBahanMasakan: "325 gr Tepung Pao Bogasari ,175 gr tepung terigu protein rendah ,100 gr gula pasir ,1/2 sdt Baking Powder ,9 gr ragi instan, 150 gr susu cair dingin ,120 gr air kelapa dingin (resep asli 104 gr) ,40 gr mentega putih ,2 gr garam ,Bahan isian Kacang / Macikwe ,250 gr kacang tanah kupas sangrai blender ,90 gr gula pasir ,35 gr mentega cair ,secukupnya Air hangat ,2 sdm wijen sangrai ,Sejumput garam", caraMasakan: "Mixer tepung, gula, ragi, baking powder, susu cair, dan air kelapa sampai setengah kalis. ,Setelah itu masukkan mentega dan garam lalu lanjut mixer sampai kalis ,Bulatkan dan diamkan 1 jam atau sampai mengembang 2 kali lipat ,Sambil menunggu adonan mengembang, buat isian kacang dengan mencampur semua isi bahan lalu diaduk rata ,Setelah adonan mengembang, kempiskan adonan dan bagi adonan sesuai selera. ,Diamkan selama 10 menit dan setelah mengembang ambil 1 adonan lalu gilas dan isi dengan 1 sdm isian kacang tanah tadi dan bentuk bakpao sesuai selera. ,Setelah semua adonan sudah diberi isi dan dibentuk, panaskan kukusan. Ketika air sudah mendidih, masukkan bakpao dan kukus sekitar 10 menit atau sampai mengembang. Jangan langsung diangkat, tunggu beberapa saat baru buka perlahan tutup pancinya dan uapnya perlahan keluar.",gambarMasakan: "BakpaoIsiKacangTanah")

//
//=============================================================================
// Kacang 3
let CreamSoupAyamJagungPolong=ResepMakanan(titleMakanan: "Cream Soup Ayam Jagung Polong", daftarBahanMasakan: "1/2 kg Dada Ayam ,1 buah Jagung manis ,1/4 Kacang polong ,1 bungkus Merica bubuk ,1 bungkus Penyedap Rasa (Masako ayam) ,3 Bawang putih ,1/2 sendok teh Garam ,1 buah Bawang bombay ,1 box Susu cair plain ,sesuai selera Keju parut ,Margarin ,Meizena", caraMasakan: "Didihkan air dan rebus dada ayam hingga matang, lalu potong-potong ayam berukuran dadu kecil, jangan buang air rebusan ayam karena akan dipakai sebagai air kaldu , Potong bawang putih dan bombay sampai halus lalu tumis potongan bawang menggunakan margarin, sampai tercium aroma bawang masukan air kaldu ayam sisa rebusan tadi. ,Masukan jagung manis, kacang polong dan ayam yang sudah dipotong dadu aduk hingga 1/2 mendidih dan masukan susu cair plain ,Aduk hingga mendidih dan masukan meizena yang sudah dilarutkan kedalam air matang lalu aduk hingga mengental (takaran meizena sesuai selera kekentalannya) ,Jika sudah mengental masukan 1 sendok teh garam, 1 bungkus penyedap rasa (saya menggunakan masako ayam), 1/2 bungkus merica bubuk ,Jika sudah matang dan rasanya cukup sesuai selera parut keju kedalam cream soup sambil diaduk-aduk hingga larut.",gambarMasakan: "CreamSoupAyamJagungPolong")
//
let SeblakPastaSpiral=ResepMakanan(titleMakanan: "Seblak Pasta Spiral", daftarBahanMasakan: "3 genggam pasta spiral ,Secukupnya kacang kapri ,1 butir telur ,1 buah tomat ,2 sdm kacang polong kalengan ,400 ml air ,Bumbu ,3 siung bawang merah ,2 siung bawang putih ,5 cm ,kencur, 1 sdm saus sambal ,1 sdm kecap manis ,Secukupnya kaldu ,Secukupnya gula ,Secukupnya garam ,Secukupnya cabe bubuk", caraMasakan: "Rendamlah pasta spiral sekitar 5 menit. Kemudian tiriskan. ,Haluskan bawang merah, bawang putih dan kencur. Kemudian tumis sampai harum. ,Masukkan air, saus sambal, kecap, kaldu, garam, dan gula. Setelah mendidih, masukkan pasta spiral. Tunggu sampai pasta matang. ,Tambahkan telur dan aduk-aduk. ,Tambahkan kacang kapri, tomat dan kacang polong. Tunggu 1 menit. ,Yang terakhir, tuang seblak yang sudah matang ke dalam mangkuk. Taburi cabe bubuk secukupnya. Seblak siap disajikan.",gambarMasakan: "SeblakPastaSpiral")
//
//=============================================================================
// Kacang 4
let SusuKedelai=ResepMakanan(titleMakanan: "Susu Kedelai", daftarBahanMasakan: "250 gram kacang kedelai ,3 liter air ,4 sdm gula pasir ,3 lembar daun pandan", caraMasakan: "Rendam kacang kedelai dengan air semalaman. ,Kupas kulit ari, sampai bersih semua lalu cuci kacang berulang kali untuk menghilangkan bau lengur. ,Belender kacang dengan air secara bertahap. Tahap pertama blender smua kacang dengan 1 L air. Saring dengan menggunakan kain lap bersih, kemudian peras sampai ampas kacang kering. Tahap kedua blender ampas kacang dengan 1 L air lagi. Saring seperti tahap pertama. Tahap ketiga blender lagi ampas kacang dengan 1 L air. Saring lagi. ,Setelah sari kacang kedelai sudah siap. Saring sekali lagi. Masukkan dalam panci, rebus dengan 3 lembar daun pandan yang sudah dicuci dan gula 4 atau 5 sdm. Selama proses merebus, susu harus selalu diaduk. ,Setelah mendidih, diamkan sebentar lalu saring dan rebus sekali lagi agar benar-benar tidak berbau lengur. ,Setelah melewati proses itu, susu sudah siap dikonsumsi. Lebih enak sajikan dingin.",gambarMasakan: "SusuKedelai")
 
let BayamTahu=ResepMakanan(titleMakanan: "Bayam Tahu", daftarBahanMasakan: "Bayam secukupnya ,2 buah tahu potong dadu ,1/2 buah cabe merah besar iris (tanpa biji) ,3 siung bawang merah iris ,1 siung bawang putih iris ,Gula pasir secukupnya ,Garam sesuai selera", caraMasakan: "Siapkan bayam, tahu, bawang iris dan cabe iris. ,Cuci bersih bayam dan tahu lalu potong ,Panaskan air dalam panci lalu aduk gula dan garam sampai mendidih. ,Saat sudah mendidih, masukan bayam lalu tahu dan aduk merata. Koreksi rasa dengan menambahkan gula atau garam sesuai selera. ,Masukkan bawang merah, bawang putih, dan cabe yang telah diiris ,Tunggu hingga bawang layu lalu angkat dan sajikan.", gambarMasakan: "BayamTahu")
